//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace listOfDishes
{
    using System;
    using System.Collections.Generic;
    using System.Data.Linq.Mapping;
    [Table(Name = "Ingridients")]
    public partial class Ingridients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingridients()
        {
            this.DishList = new HashSet<DishList>();
        }
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int ID { get; set; }
        [Column]
        public string Title { get; set; }
        [Column]
        public int Proteins { get; set; }
        public int Fats { get; set; }
        [Column]
        public int Carbohydrates { get; set; }
        [Column]
        public Nullable<int> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishList> DishList { get; set; }
    }
}
